# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 73362edcc654285e21efcd4209424cd96e99f6afee72e7dc6a98349c6f6ca58354167a6ffbd23913637925a90a2a15be936212aa676648c8bcead78319c443fa

test:
  secret_key_base: 93c91d7ee38d4717cc4aa00586c1ece987c9ae1a0cb3f0ade4aee72799b0c1106f4c6fef56a7279be3ea0403bf1acb653fcc80eb24a8c522a19379630416023f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
